# Azure Pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines

trigger:
  branches:
    include:
    - master
    - dev
  tags:
    include: 
    - '*'

stages:
- stage: Build   
  jobs:
  - template: jobs/build.yml
    parameters:
      name: Windows
      platform: win
      pool:
        vmImage: 'windows-latest'

  - template: jobs/build.yml
    parameters:
      name: Linux
      platform: linux
      pool:
        vmImage: 'ubuntu-latest'

  - template: jobs/build.yml
    parameters:
      name: MacOS
      platform: mac
      pool:
        vmImage: 'macOS-latest'

- stage: Test
  dependsOn: Build
  jobs:
  - template: jobs/test.yml

- stage: Release
  dependsOn: Build
  jobs:
  - template: jobs/release.yml
