# Gradle
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  name: ''
  pool: ''
  platform: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'jlinkZip'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'build-output'
        pathToPublish: '$(System.DefaultWorkingDirectory)/build/distributions/boundingboxeditor-${{ parameters.platform }}.zip'